<?php 
/**
 * Implements hook_menu().
 */
function myrender_example_menu() {
  $items['examples/myrender_example'] = array(
    'title' => 'My Render Example',
    'page callback' => 'myrender_example_pageinfo',
    'access callback' => TRUE,
  );
  
 
   return $items;
}


function myrender_example_pageinfo() {
    /*
      * Simple example of htm output
  
     $demo= array(
             '#markup' => t('Hello renderer!'),
           );
   * */
  
     /*
      * this is actually using theme_item_list() in includes/theme.inc
  
  
     $demo= array(
             '#theme' => 'item_list',
             '#items' => array('Item 1', 'Item 2', 'Item 3'),
         );
     * */
  /**
  $demo= array(
      'some_text' => array(
          '#markup' => t('This is the block body1'),
  
      ),
  
      'just_a_list_of_links' => array(
          '#theme' => 'item_list',
          '#items' => array('Item 1', 'Item 2', 'Item 3'),
          '#title' => t('My item list'),
          '#type' => 'ol',
      ),
      'some_other_text' => array(
          '#markup' => t('This is the block body1'),
  
      ),
  
  );
  
  **/
  
     /*
     * theme
      * */
  
  /*
     $demo= array(
             '#theme' => 'item_list',
             '#items' => array('Item 1', 'Item 2', 'Item 3'),
             '#title' => t('My item list'),
             '#type' => 'ol',
         );
         
  
  
 */
  $progress = 50;
  $demo= array(
      'some_text' => array(
          '#markup' => t('This is the block body'),
      ),
  
      'just_a_list_of_links' => array(
          '#theme' => 'example_link_list',
          '#children' => array(
              0 => array(
                  'label' => t('Step 1'),
                  'url' => 'http://www.example.com/1',
              ),
              1 => array(
                  'label' => t('Step 2'),
                  'url' => 'http://www.example.com/2',
              ),
          ),
      ),
      'nice_looking_progress_bar' => array(
          '#theme' => 'example_progress_bar',
          '#progress' => $progress,
      ),
      
  
  );


  return $demo;
  
}

/**
 * Provides a number of render arrays and show what they do.
 *
 * Each array is keyed by a description; it's returned for rendering at page
 * render time. It's easy to add new examples to this.
 *
 * The array items in $demos are intended to be raw, normal render arrays
 * that can be experimented with to end up with different outcomes.
 */
function myrender_example_arrays() {
  
  $demos = array(
  // Demonstrate the simplest markup, a #markup element.
      t('Super simple #markup')  => array(
          '#markup' => t('Some basic text in a #markup (shows basic markup and how it is rendered)'),
      ),
      );
  // The rest of this function just places the above arrays in a context where
  // they can be rendered (hopefully attractively and usefully) on the page.
  $page_array = array();
  foreach ($demos as $key => $item) {
 //   $page_array[$key]['#theme_wrappers'] = array('render_array');
    $page_array[$key]['#description'] = $key;
  
    
  }
  
  return $page_array;
}

/**
 * Themes the render array (from the demonstration page).
 */
function theme_render_array($variables) {
  $heading = '<div class="render-header">' . $variables['element']['#description'] . '</div>';

  $rendered = '<div class="render-array">' . $heading . $variables['element']['#children'] . '</div>';
  return $rendered;

}

/**
 * Implements hook_theme().
 */

function myrender_example_theme()
{
  return array(
      'example_link_list' => array(
          'render element' => 'links',
      ),
      'example_progress_bar' => array(
          'variables' => array(
              'progress' => NULL,
          ),
      ),
  );
  
}

/**
 * Theme implementation
 * */
/**
 * Displays a list of links.
 */
function theme_example_link_list($variables = array()) {
 
  $links = array();
  foreach ($variables['links']['#children'] as $link) {
    $links[] = l($link['label'], $link['url']);
  }
  
  var_dump($links);
  return theme('item_list', array('items' => $links));
}

/**
 * Displays a progress bar.
 */
function theme_example_progress_bar($variables = array()) {
  return '<div id="example-progress-bar">' . $variables['progress'] . '%</div>';
}
