<?php


/**
 * Implements hook_menu().
 *
 * Provide a menu item and a page to demonstrate features of this example
 * module.
 */
function multifiles_example_menu() {
  $items = array();
  $items['multifiles_example'] = array(
    'title' => 'Multifiles Example',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('multifiles_example_form'),
    'access arguments' => array('access content'),
    'file' => 'multifiles_example.pages.inc',
  );
  
}






/**
 * Implements hook_theme().
 
function multifiles_example_theme() {
  return array(
    'image_example_colorize_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'image_example_image' => array(
      'variables' => array('image' => NULL, 'style' => NULL),
      'file' => 'image_example.pages.inc',
    ),
  );
}

*/

/**
 * Formats a summary of an image colorize effect.
 *
 * @param $variables
 *   An associative array containing:
 *   - data: The current configuration for this colorize effect.

function theme_image_example_colorize_summary($variables) {
  $data = $variables['data'];
  return t('as color #@color.', array('@color' => $data['color']));
}

 */


