<?php 
/**
 * @file
 * A node module that defines a node type: .
 */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function ccruby_help($path, $arg) {
	
}


/**
 * Implements hook_menu().
 *
 * We are providing a default page to illustrate the use of our custom node view mode that will 
 * live at http://example.com/?q=examples/node_example
 *
 

function ccruby_menu() {
	
	
}

*/

/*
 *hook_menu_alter 
 */
function ccruby_menu_alter(&$items)
{
  // to only display it in secondary menu when user is logged in  
  $items['user']['access callback'] = 'user_is_logged_in';
  
  //get the titile back by making it a normal menu item 
  $items['user/login']['type'] = MENU_NORMAL_ITEM;
  
  //get the titile back by making it a normal menu item
  $items['user/register']['type'] = MENU_NORMAL_ITEM;
     
  
  
  
}

function ccruby_menu()
{
  // Registration and login pages.
  $items['ccruby/%user'] = array(
      'title' => 'My Profile',
      'page callback' => 'user_view_page',
      'page arguments' => array(1),
      'access callback' =>'user_view_access',
      'access arguments' => array(1),
      'menu_name' => 'main-menu',
  );
  
  
  $items['ccruby/%user/edit'] = array(
      'title' => 'Edit',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('user_profile_form', 1),
      'access callback' => 'user_edit_access',
      'access arguments' => array(1),
  );
  
  $items['ccruby/%user/cancel'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_cancel_confirm_form', 1),
    'access callback' => 'user_cancel_access',
    'access arguments' => array(1),
  );
  
  $items['ccruby/%user/cancel/confirm/%/%'] = array(
      'title' => 'Confirm account cancellation',
      'page callback' => 'user_cancel_confirm',
      'page arguments' => array(1, 4, 5),
      'access callback' => 'user_cancel_access',
      'access arguments' => array(1),
  );
  
  
  return $items;
  
}
