<?php 
/**
 * @file
 * A node module that defines a node type: .
 */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function ccruby_help($path, $arg) {
	
}


/**
 * Implements hook_menu().
 *
 * We are providing a default page to illustrate the use of our custom node view mode that will 
 * live at http://example.com/?q=examples/node_example
 *
 

function ccruby_menu() {
	
	
}

*/

/*
 *hook_menu_alter 
 */
function ccruby_menu_alter(&$items)
{
  //items when user logged in
  // to only display it in secondary menu when user is logged in  
  $items['user']['access callback'] = 'user_is_logged_in';
  $items['user']['title'] ='funny';
  $items['user']['menu_name'] ='secondary_top';
  
  $items['user/logout']['menu_name'] ='secondary_top';
  
  // items for not logged in
  
  //get the titile back by making it a normal menu item
  $items['user/login']['type'] = MENU_NORMAL_ITEM;
  $items['user/login']['weight'] =10;
  $items['user/login']['menu_name'] ='secondary_top';
  
  //get the titile back by making it a normal menu item
  $items['user/register']['type'] = MENU_NORMAL_ITEM;
  $items['user/register']['title'] ='Sign up';
  $items['user/register']['weight'] =15;
  $items['user/register']['menu_name'] ='secondary_top';
  
}

/*
function ccruby_menu()
{
 
  
  return $items;
  
}
*/
