<?php 
/**
 * @file
 * A node module that defines a node type: .
 */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function ccruby_help($path, $arg) {
	
}


/**
 * Implements hook_menu().
 *
 * We are providing a default page to illustrate the use of our custom node view mode that will 
 * live at http://example.com/?q=examples/node_example
 *
 

function ccruby_menu() {
	
	
}

*/

/*
 *hook_menu_alter 
 */
function ccruby_menu_alter(&$items)
{
  // to only display it in secondary menu when user is logged in  
  $items['user']['access callback'] = 'user_is_logged_in';
  
  //get the titile back by making it a normal menu item 
  $items['user/login']['type'] = MENU_NORMAL_ITEM;
  
  //get the titile back by making it a normal menu item
  $items['user/register']['type'] = MENU_NORMAL_ITEM;
     
}

function ccruby_menu()
{
  // Registration and login pages.
  $items['ccruby'] = array(
      'title' => 'My Account',
      
      'access callback' => true,
  );
  
  return $items;
  
}
