<?php

/**
* @file
* A block module that displays recent blog and forum posts.
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/

function current_posts_help($path, $arg) {
  switch ($path) {
    case "admin/help#current_posts":
      return '<p>'.  t("Displays links to nodes created on this date") .'</p>';
      break;
  }
} 


/**
* Implements hook_block_info().
*/
function current_posts_block_info() {
  $blocks['current_posts'] = array(
    'info' => t('Johnson current posts'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

/**
* Custom content function.
*
* Set beginning and end dates, retrieve posts from database
* saved in that time period.
*
* @return
*   A result set of the targeted posts.
*/
function current_posts_contents($display){
  //Get today's date.
  $today = getdate();
  //Calculate the date a week ago.
  $start_time = mktime(0, 0, 0,$today['mon'],($today['mday'] - 7), $today['year']);
  //Get all posts from one week ago to the present.
  $end_time = time();
  
  $max_num = variable_get('current_posts_max', 3);
  
  //Use Database API to retrieve current posts.
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('status', 1) //Published.
    ->condition('changed', array($start_time, $end_time), 'BETWEEN')
    ->orderBy('created', 'DESC'); //Most recent first.
   
   if ($display == 'block'){
  	// Restrict the range if called with 'block' argument.
    $query->range(0, $max_num);
   } //Now proceeds to execute().
      
  return $query->execute();
   
}

function current_posts_block_view($delta = '') {
  switch($delta){
    case 'current_posts':
      
      $block['subject'] = t('Johnson current posts22222222');
      
      if(user_access('access content')){
       //Retrieve and process data here.
       //Use our custom function to retrieve data.
        $result = current_posts_contents('block');
        
        //Array to contain items for the block to render.
        $items = array();
        //Iterate over the resultset and format as links.
        foreach ($result as $node){
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          );
      	}
      	
      	if (empty($items)) { //No content in the last week.
         		$block['content'] = t('No posts available.'); 
        } 
        else{
          	
        //Pass data through theme function.
  			$block['content']['posts'] = array(
    			'#theme' => 'item_list__current_posts__block',
    			'#items' => $items,
  			); 
  			
  			//Add a link to the page for more entries.
  			$block['content']['more'] = array(
    			'#theme' => 'more_link__current_posts',
    			'#url' => 'current_posts',
    			'#title' => t('See the full list of current posts.'),
  			);
        }
   
        
       }
   }
   return $block;
} 

/**
* Implements hook_menu().
*/
function current_posts_menu() {
  $items = array(); 

  $items['admin/config/content/current_posts'] = array(
    'title' => 'Johnson current posts',
    'description' => 'Configuration for Current posts module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('current_posts_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
 
  $items['current_posts'] = array(
    'title' => 'Johnson current posts',
    'page callback' => '_current_posts_page',
    'access arguments' => array('access johnson_current_posts content'),
    'type' => MENU_CALLBACK, //Will appear in Navigation menu.
  );
  
  return $items;
}  

/**
* Form function, called by drupal_get_form()
* in current_posts_menu().
*/
function current_posts_form($form, &$form_state) {
  $form['current_posts_max'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of posts'),
    '#default_value' => variable_get('current_posts_max', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('The maximum number of links to display in the block.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
* Implements validation from the Form API.
*
* @param $form
*   A structured array containing the elements and properties of the form.
* @param $form_state
*   An array that stores information about the form's current state
*   during processing.
*/
function current_posts_form_validate($form, &$form_state){
  $max_num = $form_state['values']['current_posts_max'];
  if (!ctype_digit($max_num)){
    form_set_error('current_posts_max', t('You must enter a number for the maximum number of posts to display.'));
  }
}

/**
* Implements hook_permission().
*/
function current_posts_permission(){
  return array(
    'access johnson_current_posts content' => array(
      'title' => t('Access content for the Johnson current posts module'),
    ) 
  ); 
}

/**
* Custom page callback function, declared in current_posts_menu().
*/
function _current_posts_page() {
  
  drupal_set_title('Johnson current posts11111111');
  
  $result = current_posts_contents('page');
  //Array to contain items for the page to render.
  
  $items = array();
  
  //Iterate over the resultset and format as links.
  foreach ($result as $node) {
    $items[] = array(
    'data' => l($node->title, 'node/' . $node->nid),
    );
  }
  
  if (empty($items)) { //No content in the last week.
    $page_array['current_posts_arguments'] = array(
      //Title serves as page subtitle
      '#title' => t('All posts from the last week'),
      '#markup' => t('No posts available.'),
    );
    }
    else {
    $page_array['current_posts_arguments'] = array(
      '#title' => t('All posts from the last week'),
      '#items' => $items,
      //Theme hook with suggestion. 
      '#theme' => 'item_list__current_posts',
    );
    }
    return $page_array; 
} 
?>